---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userdefinednetworks.k8s.ovn.org
spec:
  group: k8s.ovn.org
  names:
    kind: UserDefinedNetwork
    listKind: UserDefinedNetworkList
    plural: userdefinednetworks
    singular: userdefinednetwork
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: UserDefinedNetwork schema
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: UserDefinedNetworkSpec defines the desired state of UserDefinedNetwork
            type: object
            properties:
              topology:
                type: string
              layer2:
                type: object
                properties:
                  role:
                    type: string
                  ipam:
                    type: object
                    properties:
                      lifecycle:
                        type: string
                  subnets:
                    type: array
                    items:
                      type: string
          status:
            description: UserDefinedNetworkStatus defines the observed state of UserDefinedNetwork
            type: object
    served: true
    storage: true
    subresources:
      status: {}

